# cons_format = "<span font_family='Font Awesome 6 Free'>{icon}</span>"

[theme]
theme = "nord-dark"
[theme.overrides]
idle_bg = "#17171c"

[icons]
icons = "awesome6"
[icons.overrides]
volume_muted = ''

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:30) $prev $play $next|}"
seek_step_secs = 10
[[block.click]]
button = "left"
action = "next_player"
[[block.click]]
button = "right"
action = "play_pause"

# [[block]]
# block = "cpu"
# info_cpu = 20
# warning_cpu = 70
# critical_cpu = 90
# format = " $barchart $utilization "

# [[block]]
# block = "memory"
# format = " $icon $mem_total_used_percents.eng(w:2)"
# format_alt = " $icon_swap $swap_used_percents.eng(w:2)"

[[block]]
block = "battery"
format = " $icon{ $percentage|}"
device = "DisplayDevice"
driver = "upower"
full_threshold = 75
[[block.click]]
button = "left"
cmd = "alacritty -T upower --hold -e upower -d"

[[block]]
block = "sound"
format = " <span font_family='Font Awesome 6 Free'>$output_name</span> {$volume|0%}"
[block.mappings]
"alsa_output.pci-0000_64_00.6.HiFi__Speaker__sink" = ""
"bluez_output.E8_EE_CC_48_B9_9C.1" = ""
[[block.click]]
button = "left"
cmd = "pavucontrol"
[block.theme_overrides]
warning_bg = "#17171c" # nord0
warning_fg = "#81a1c1" # light blue

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid|}"

[[block]]
block = "time"
interval = 60
format = " <span font-family=\"Courier Prime\" ><b>$timestamp.datetime(f:'%a') <span size=\"x-large\">$timestamp.datetime(f:'%d')</span> $timestamp.datetime(f:'%b') <span size=\"x-large\">$timestamp.datetime(f:'%R')</span></b></span> "

